services:
  tnn-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        NEXT_PUBLIC_NEWS_API_KEY: ${NEXT_PUBLIC_NEWS_API_KEY}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

# setup your .env file and run this command in the same folder or in the root of your project
# docker compose --env-file .env up --build
